openapi: 3.2.0
info:
  title: Weaviate REST API
  description: '# Introduction

    Weaviate is an open source, AI-native vector database that helps developers create intuitive and reliable AI-powered applications.'
  version: 1.38.0-dev
servers:
- url: http://localhost:8080
  description: Local Weaviate instance
security:
- ApiKeyAuth: []
- BearerAuth: []
tags:
- name: Weaviate REST API
paths:
  /:
    get:
      summary: Weaviate List Available Endpoints
      description: Get links to other endpoints to help discover the REST API.
      operationId: weaviate.root
      responses:
        '200':
          description: Weaviate is alive and ready.
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      $ref: '#/components/schemas/Link'
      x-microcks-operation:
        delay: 100
      tags:
      - Weaviate REST API
components:
  schemas:
    Link:
      type: object
      properties:
        href:
          type: string
          description: Target of the link.
        rel:
          type: string
          description: Relationship if both resources are related, e.g. 'next', 'previous', 'parent', etc.
        name:
          type: string
          description: Human readable name of the resource group.
        documentationHref:
          type: string
          description: Weaviate documentation about this resource group.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: API key authentication
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OIDC/JWT bearer authentication
