openapi: 3.0.3
info:
  title: Weaviate REST authz Weaviate REST API API
  description: '# Introduction<br/> Weaviate is an open source, AI-native vector database that helps developers create intuitive and reliable AI-powered applications. <br/> ### Base Path <br/>The base path for the Weaviate server is structured as `[YOUR-WEAVIATE-HOST]:[PORT]/v1`. As an example, if you wish to access the `schema` endpoint on a local instance, you would navigate to `http://localhost:8080/v1/schema`. Ensure you replace `[YOUR-WEAVIATE-HOST]` and `[PORT]` with your actual server host and port number respectively. <br/> ### Questions? <br/>If you have any comments or questions, please feel free to reach out to us at the community forum [https://forum.weaviate.io/](https://forum.weaviate.io/). <br/>### Issues? <br/>If you find a bug or want to file a feature request, please open an issue on our GitHub repository for [Weaviate](https://github.com/weaviate/weaviate). <br/>### Need more documentation? <br/>For a quickstart, code examples, concepts and more, please visit our [documentation page](https://docs.weaviate.io/weaviate).'
  version: 1.38.0-dev
servers:
- url: http://localhost:8080
  description: Local Weaviate instance
security:
- ApiKeyAuth: []
- BearerAuth: []
tags:
- name: Weaviate REST API
paths:
  /:
    get:
      summary: Weaviate List Available Endpoints
      description: Get links to other endpoints to help discover the REST API.
      operationId: weaviate.root
      responses:
        '200':
          description: Weaviate is alive and ready.
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      $ref: '#/components/schemas/Link'
      x-microcks-operation:
        delay: 100
      tags:
      - Weaviate REST API
components:
  schemas:
    Link:
      type: object
      properties:
        href:
          type: string
          description: Target of the link.
        rel:
          type: string
          description: Relationship if both resources are related, e.g. 'next', 'previous', 'parent', etc.
        name:
          type: string
          description: Human readable name of the resource group.
        documentationHref:
          type: string
          description: Weaviate documentation about this resource group.
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: API key authentication
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: OIDC/JWT bearer authentication
